[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

# Prevent direct access to functions from crawlers
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    X-Robots-Tag = "noindex"

# Basic redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {not = "/.netlify/functions/*"}